# Generated by Django 4.2.7 on 2023-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='page',
            name='img_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
